https://editor.p5js.org/william.kim1/sketches/aYfHgKQFB
https://editor.p5js.org/william.kim1/sketches/aYfHgKQFB
https://editor.p5js.org/william.kim1/sketches/ye2NMnIOE
https://editor.p5js.org/william.kim1/sketches/08LzEEpe5

These sketches create various maws in a variety of patterns
The first creates a single maw
The second creates multiple maws
The thrid creates randomized maws
The fourth creates randomized maws with a set order
